### ISSUE TITLE
Run complete issue for contact page

### ISSUE THREAD

**Issue by VKongkin** [SokmengKong1/project_test_gits#25]
Please create a contact page in **src/contact** and complete with header, navbar, menu and footer.

Note please use branch *feature/contact as your master branch.

Process these in cherry pick method

**Comment by runnd** [comment]
Done create header, navbar, menu and footer to src/contact
Cherrypick to main branch feature/contact
Kindly check:
[feature/contact](https://github.com/SokmengKong1/project_test_gits/tree/feature/contact/src/contact)
[src/contact/header.js](https://github.com/SokmengKong1/project_test_gits/blob/feature/contact/src/contact/header.js)
[src/contact/navbar.js](https://github.com/SokmengKong1/project_test_gits/blob/feature/contact/src/contact/navbar.js)
[src/contact/menu.js](https://github.com/SokmengKong1/project_test_gits/blob/feature/contact/src/contact/menu.js)
[src/contact/footer.js](https://github.com/SokmengKong1/project_test_gits/blob/feature/contact/src/contact/footer.js)

**Comment by VKongkin** [comment]
Good
