### ISSUE TITLE
Meng complete issue for news page

### ISSUE THREAD

**Issue by VKongkin** [SokmengKong1/project_test_gits#27]
Please create a contact page in src/news and complete with header, navbar, menu and footer.

Note please use branch *feature/news as your master branch.

Process these in cherry pick method

**Comment by SokmengKong1** [comment]
Done create header, navbar, menu and footer to src/news
Cherrypick to main branch feature/new
Kindly check:
feature/news

- feature/news-header
- feature/news-navbar
- feature/news-nemu
- feature/news-footer

**Comment by VKongkin** [comment]
Good nemu
