### ISSUE TITLE
Mr Nang complete issue for events page

### ISSUE THREAD

**Issue by VKongkin** [SokmengKong1/project_test_gits#28]
Please create a events page in **src/events** and complete with header, navbar, menu and footer.
បង្កើត events page នៅក្នុង src => src/events ហើយបង្កើត header, navbar, menu និង footer ដាក់ក្នុង src/events

Note please use branch *feature/events as your master branch.
ចំណាំ: ត្រូវបង្កើតចេញពី Branch feature/events

Process these in cherry pick method
ប្រើប្រាស់វិធីសាស្ត្រ cherry pick

**Comment by SomSamnang** [comment]
create a events page in src/events and complete with header, navbar, menu and footer.
បង្កើត events page នៅក្នុង src => src/events ហើយបង្កើត header, navbar, menu និង footer ដាក់ក្នុង src/events
 use branch *feature/events as your master branch.
ចំណាំ: ត្រូវបង្កើតចេញពី Branch feature/events

Process these in cherry pick method
ប្រើប្រាស់វិធីសាស្ត្រ cherry pick

ខ្ញុំបានធ្វើរួចហើយ សូមជួយត្រួតពិនិត្យមើលកិច្ចការរបស់ខ្ញុំម្តងទៀតផង អរគុណច្រើន

**Comment by SomSamnang** [comment]
create a events page in src/events and complete with header, navbar, menu and footer.
បង្កើត events page នៅក្នុង src => src/events ហើយបង្កើត header, navbar, menu និង footer ដាក់ក្នុង src/events
use branch *feature/events as your master branch.
ចំណាំ: ត្រូវបង្កើតចេញពី Branch feature/events

Process these in cherry pick method
ប្រើប្រាស់វិធីសាស្ត្រ cherry pick

ខ្ញុំបានធ្វើរួចហើយ សូមជួយត្រួតពិនិត្យមើលកិច្ចការរបស់ខ្ញុំម្តងទៀតផង អរគុណច្រើន

**Comment by SomSamnang** [comment]
create a events page in src/events and complete with header, navbar, menu and footer.
បង្កើត events page នៅក្នុង src => src/events ហើយបង្កើត header, navbar, menu និង footer ដាក់ក្នុង src/events
use branch *feature/events as your master branch.
ចំណាំ: ត្រូវបង្កើតចេញពី Branch feature/events

Process these in cherry pick method
ប្រើប្រាស់វិធីសាស្ត្រ cherry pick

ខ្ញុំបានធ្វើរួចហើយ សូមជួយត្រួតពិនិត្យមើលកិច្ចការរបស់ខ្ញុំម្តងទៀតផង អរគុណច្រើន

**Comment by VKongkin** [comment]
good
